### ISSUE TITLE
映射结果问题

### ISSUE THREAD

**Issue by openaddr** [ClearPlume/jimmer-generator#2]
转化kotlin
数据库中是:
int
decimal(24)
期望得到的是:
Integer
Bigdecimal
但实际得到的是:
Any
Any

**Comment by openaddr** [comment]
github不知道为什么, 我的截图上传一直失败, 没办法提供截图...
但情况确实如我所描述一般;
或许可以考虑提供映射的配置能力?

**Comment by ClearPlume** [comment]
已经修改完成，但我这边的情况可能没法测试...你用的啥数据库？我看看能不能装一个

**Comment by ClearPlume** [comment]
我用MySQL测试了修复结果，你等等0.3.8确定一下...我不知道你用的是什么数据库

> Java

![Java](https://github.com/ClearPlume/jimmer-generator/assets/18047536/de8cf568-7635-45a5-9241-d346cfe7597e)

> Kotlin

![Kotlin](https://github.com/ClearPlume/jimmer-generator/assets/18047536/dc1cb351-f8a6-444d-87d4-1d28b7d5ffa8)

**Comment by openaddr** [comment]
好的, 我也使用的Mysql, 现在正确地对应了 int 和decimal类型了!

**Comment by openaddr** [comment]
或许可以在全局配置默认的 逻辑删除字段, 
如果数据库是规范的话, 那应该一个系统中, 逻辑删除字段总是相同的 ;
可以考虑全局配置逻辑删除字段的数据库字段名;
例如:
通用逻辑删除字段名: is_deleted
逻辑删除值:  true    //或者对应类型的值即可, 反正jimmer是以字符串接受的
用户设置了此属性后, 为每个生成的接口的对应字段添加逻辑删除的注解
例如:
    @LogicalDeleted("true")
    val isDeleted: Boolean

**Comment by ClearPlume** [comment]
> 或许可以在全局配置默认的 逻辑删除字段, 如果数据库是规范的话, 那应该一个系统中, 逻辑删除字段总是相同的 ; 可以考虑全局配置逻辑删除字段的数据库字段名; 例如: 通用逻辑删除字段名: is_deleted 逻辑删除值: true //或者对应类型的值即可, 反正jimmer是以字符串接受的 用户设置了此属性后, 为每个生成的接口的对应字段添加逻辑删除的注解 例如: @LogicalDeleted("true") val isDeleted: Boolean

逻辑删除我也正在设计，你的想法我会参考...感觉会很有帮助，多谢！

**Comment by ClearPlume** [comment]
> 好的, 我也使用的Mysql, 现在正确地对应了 int 和decimal类型了!

Fixed in 0.3.8.
